### Data Structures

In [ ]:
#Data Structures & Control Structures

In [1]:

# 1.Create a list of 5 integers

nums = [20,30,40,50,60]
print("Before updating the list: ",nums)
#append() method is used for adding element at end of list

nums.append(70)
print("After append a 70 element in the list: ",nums)

#extend() method is used for adding multiple elements at end of list

nums.extend([80,90])
print("After extends the elements(80,90) in the list: ",nums)

#insert() method is used for insert element at specific place or specific index value in a list

nums.insert(0,10)
print("After insert a 10 value in the list: ",nums)

#remove() method is used for remove the specific element in the list

nums.remove(90)
print("After remove a 90 element in the list: ",nums)

#pop() method is used for delete the element at end of the list

nums.pop()
print("After pop a element in the list:",nums)

#index() method is used for to find the index value at specific element position

index_value = nums.index(50)
print("50 element index value is: ",index_value)

#count() method is used for count the how many elements in the list

count_values = nums.count(60)
print("How many elements in the list(60): ",count_values)

#sort() method is used for arrange the data in order 

nums.sort()
print("Sort the ascending order in list: ",nums)

#reverse() method is used for reverse the list

nums.reverse()
print("Revere the list: ",nums)

#clear() method is used for delete all elements in the list

nums.clear()
print("Clear a list: ",nums)

Before updating the list:  [20, 30, 40, 50, 60]
After append a 70 element in the list:  [20, 30, 40, 50, 60, 70]
After extends the elements(80,90) in the list:  [20, 30, 40, 50, 60, 70, 80, 90]
After insert a 10 value in the list:  [10, 20, 30, 40, 50, 60, 70, 80, 90]
After remove a 90 element in the list:  [10, 20, 30, 40, 50, 60, 70, 80]
After pop a element in the list: [10, 20, 30, 40, 50, 60, 70]
50 element index value is:  4
How many elements in the list(60):  1
Sort the ascending order in list:  [10, 20, 30, 40, 50, 60, 70]
Revere the list:  [70, 60, 50, 40, 30, 20, 10]
Clear a list:  []


In [2]:
# 2.Create a tuple that stores 3 student names

student_names = ("Balaji","vishnu","Sri Ram")
student_names[1] = "Sandeep Kisan"
print(student_names)

# NOTE: it will raise an type error,because tuple is a immutable 

TypeError: 'tuple' object does not support item assignment

### Explaination
A tuple is immutable, which means its elements cannot be changed, added, or removed after the tuple is created.

In [3]:
# 3.create a SET of integers with some duplicates

numbers = {12,14,15,16,14,12,17,17}
print(numbers)

# NOTE: sets is unique values,unordered, and allowed a duplicated values.

{16, 17, 12, 14, 15}


### Explaination
A set stores only unique values. Duplicate values are automatically removed.

In [5]:
# 4.Create a dictionary 

person_detail = {"Name":"koduru balaji","AGE":22,"CITY":"Nellore"}
print(person_detail) 

person_detail["AGE"] = 23
print("Modify the age is 22 to 23:")
print(person_detail)

person_detail["E-MAIL"] = "balaji1234@gmail.com"
print("Adding email column in person_detail dictionary:")
print(person_detail)

{'Name': 'koduru balaji', 'AGE': 22, 'CITY': 'Nellore'}
Modify the age is 22 to 23:
{'Name': 'koduru balaji', 'AGE': 23, 'CITY': 'Nellore'}
Adding email column in person_detail dictionary:
{'Name': 'koduru balaji', 'AGE': 23, 'CITY': 'Nellore', 'E-MAIL': 'balaji1234@gmail.com'}


In [9]:
# 5.Checks a your eligible for voting or not

age = int(input("Enter a your age:"))

if age >= 18:
    print("Your are eligible for voting")
else:
    print("Your are not eligible for voting")

Enter a your age: 18


Your are eligible for voting


In [10]:
# 6.checking for grade with marks

marks = int(input("Enter a your marks:"))

if marks >= 90:
    print("Your Grade is: A")
elif marks >= 75 and marks <= 89:
    print("Your Grade is: B")
elif marks >= 50 and marks <= 74:
    print("Your Grade is: C")
else:
    print("Fail")

Enter a your marks: 100


Your Grade is: A


In [11]:
# 7. Check a number if it positive and even.if not positive its a zero or negative

number = int(input("Enter a number:"))

if number > 0:
    print("number is positive")
    if number % 2 == 0:
        print("its even number")
    else:
        print("its odd number")
elif number < 0:
    print("number is a negative")
else:
    print("it is a zero")

Enter a number: 4


number is positive
its even number


### Numpy

In [13]:
# NUMPY
# 8. Create numpy array

# importing the numpy 

import numpy as np

# A scalar using np.array(5)

arr = np.array(5)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print("******************************")
# A 1D array with values 1 to 5

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print("******************************")
# A 2D array (2x3) with values from 10 to 60 in steps of 10 

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

5
<class 'numpy.ndarray'>
0
()
******************************
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
******************************
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
(2, 3)


In [14]:
# 9. Generate a 4x4 numpy array of random integers between 0 and 100

import numpy as np

matrix = np.random.randint(0,101,(4,4))
print(matrix)

[[ 9 58 65 71]
 [ 2  5  3 92]
 [23 55 37 73]
 [ 3 36 31 79]]


In [15]:
# 10. Create a 2D numpy array of shape(3x3).Convert it into pandas data frame and add columns names

#import numpy and pandas

import numpy as np
import pandas as pd

# Create a 3x3 numpy array

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

print("****************************************")

# Convert numpy into pandas dataframe

df = pd.DataFrame(arr)
print(df)

print("****************************************")

# add Columns names is A,B,C

df.columns = ['A','B','C']
print(df)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
****************************************
    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90
****************************************
    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


###  Exploring Pandas

In [16]:
# 11. Create a small Dataframe manually with 10 rows and columns

# import pandas

import pandas as pd

# Create a dataframe

df = pd.DataFrame({'Name':['koduru balaji','vijay','sandeep kishan','Sri Ram','Varun','Kumar','Bhuvan','Sai','Pavan','Ram'],
                   'Age':[22,23,22,18,26,25,34,21,27,24],
                   'City':['Nellore','Vijayawada','Kadapa','Krishna','Hyderabad','Guntur','Vizayanagaram','sanathnagar','Palanadu','chittor'],
                   'Salary':[25000,26000,28000,30000,32000,34000,36000,38000,40000,42000]
                  })
print(df)
print("#######################################")

# use info() and describe()

print(df.info())
print("#######################################")
print(df.describe())
print("#######################################")

#select 'Name' and 'City' columns

print(df[['Name','City']])
print("#######################################")

#Drop 'City' column

df = df.drop('City',axis = 1)
print(df)



#fill any missing values in 'Salary' column with the mean

print("How many missing values is: ",df['Salary'].isnull().sum())



#Remove any duplicated rows

print("How many duplicated rows: ",df.duplicated().sum())


             Name  Age           City  Salary
0   koduru balaji   22        Nellore   25000
1           vijay   23     Vijayawada   26000
2  sandeep kishan   22         Kadapa   28000
3         Sri Ram   18        Krishna   30000
4           Varun   26      Hyderabad   32000
5           Kumar   25         Guntur   34000
6          Bhuvan   34  Vizayanagaram   36000
7             Sai   21    sanathnagar   38000
8           Pavan   27       Palanadu   40000
9             Ram   24        chittor   42000
#######################################
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes
None
#######################################
             Age       Salary
count  